### ISSUE TITLE
Please consider using a plain JS file as the main export

### ISSUE THREAD

**Issue by gaearon** [dfcreative/color-name#5]
[Webpack does not support `require()`ing JSON with its default configuration.](https://github.com/MoOx/color-string/issues/20#issuecomment-143018346) This is problematic because I can't depend on `color-name` (or any its dependents) because if they use Webpack, they won't be able to consume my library without configuring JSON support.

Please consider changing the export to be a plain JS module. I understand this seems to be a Webpack's issue, but Webpack has no intention to fix it, and right now the only outcome is that Webpack consumers, or library authors who care about Webpack consumers, can't use `color-name` or any its dependent.

**Comment by dfcreative** [comment]
@gaearon please see related PR discussion https://github.com/dfcreative/color-name/pull/3

**Comment by gaearon** [comment]
Oh, I see. Unfortunately I can't ask consumers of my library (in which `color` usage is implementation detail) to configure `json-loader` just because I happen to rely on it internally.

**Comment by dfcreative** [comment]
@gaearon for browserify, actually, it is possible to point some configuration in per-module package.json, for example:
```json
  ...
  "browserify": {
    "transform": [
      "babelify"
    ]
  },
  ...
```
In that case consumers of modules shouldn’t care about configuration of their json’s, browserify just bundles all well.
Is there the same directive for webpack? I could’ve just added it to let webpack know that this should be considered as a json?

**Comment by gaearon** [comment]
No, Webpack assumes you don't want to spend the build time building dependencies (and potentially getting weird errors e.g. when Babel ships a bug) so there is no way to specify the required transforms in package. It's always up to the consumer what to transform and how, and it is assumed that NPM packages ship directly consumable code.

**Comment by dfcreative** [comment]
json requirements is a consumable code, it is just the webpack who cannot consume it. There are other packages using json-requirements within (such as [dog-names](https://github.com/sindresorhus/dog-names) etc.) which are not able to be used by webpack that simply.
So seems that is the price of using webpack - pointing all needed in config. Sorry...
